version: '2.1'

services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 # the port on which ZooKeeper will listen for client connections (2181).
      ZOOKEEPER_SERVER_ID: 1 # The server ID for this ZooKeeper instance (1).
      ZOOKEEPER_SERVERS: zoo1:2888:3888
      # Specifies the ZooKeeper servers in the ensemble.
      # In this case, it is just the single server zoo1 with port mappings for leader election and communication (2888:3888).

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092" # for the Kafka broker.
      - "29092:29092" # for Docker internal access.
      - "9999:9999" # for JMX monitoring.
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT # Maps listener names to security protocols.
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL # Specifies the listener name for inter-broker communication (INTERNAL).
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181" #Specifies the ZooKeeper connection string (zoo1:2181).
      KAFKA_BROKER_ID: 1 #Sets the broker ID (1).
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 #Sets the replication factor for the offsets topic (1).
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 #  Sets the replication factor for the transaction state log (1).
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 # Sets the minimum in-sync replicas for the transaction state log (1).
      KAFKA_JMX_PORT: 9999 # Sets the JMX port (9999).
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1} #  Sets the JMX hostname, using the Docker host IP or defaulting to 127.0.0.1.
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer # Specifies the authorizer class name for ACLs.
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true" # Allows access if no ACL is found (true).
    depends_on:
      - zoo1


